vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 1
  }
}

classes: {
  read: {
    style: {
      stroke: green
    }
  }
}

Legend: {
  MasterData: Master Data
  ReadData: Read Data {class: read}

  Field <- MasterData: relationship
  MasterData -> ReadData: streaming communication {class: read}
}

ТестированиеНайм: Тестирование и найм {
  Кандидат -> Заявка: один
  Воркер <- Кандидат: ноль или один
  Кандидат -> Результат: много
  Тест -> Результат: один
  НаборТестов -> Тест: много

  НаборТестов: Набор тестов
}

Заказы: {
  Клиент -> Заказ: много
  Заказ -> Статус: один
  Заказ -> Стоимость: один
  Заказ -> Воркер: один

  Воркер <- _.ТестированиеНайм.Воркер: {class: read}
  Воркер: {class: read}
}

Склад: {
  ЗаказНаСборку -> Отметка о выполнении: один

  ЗаказНаСборку <- _.Заказы.Заказ: {class: read}
  ЗаказНаСборку: Заказ на сборку {class: read}
}

Задачи: {
  Задача -> ОтметкаНачал: один
  ОтметкаНачал -> Фотография: один
  Задача -> ОтметкаВыполнил: один
  ОтметкаВыполнил -> Акт: один

  Задача <- _.Заказы.Заказ: {class: read}
  Задача: {class: read}

  ОтметкаНачал: Отметка о начале работы
  ОтметкаВыполнил: Отметка о выполнении работы
}

КонтрольКачества: Контроль качества {
  Заказ -> Отчет: один

  Заказ <- _.Заказы.Заказ: {class: read}
  Заказ: {class: read}
}

Билинг: {
  Клиент -> Способ оплаты: один
  Клиент -> Счет на оплату клиента: много
  Клиент -> Скидка: один
  Воркер -> Счет в Золотой шляпе: один
  Воркер -> Счет на выплату воркеру: много
  Воркер -> Баланс: один

  Клиент <- _.Заказы.Клиент: {class: read}
  Клиент: {class: read}
  Воркер <- _.ТестированиеНайм.Воркер: {class: read}
  Воркер: {class: read}
}

Тотализатор: {
  Заказ -> Ставка менеджера: много

  Заказ <- _.Заказы.Заказ: {class: read}
  Заказ: {class: read}
}
