vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 1
  }
}


Тестирование и найм -> Матчинг: синхронно

Управление заказами клиентов <- Управление расчетами с клиентами: синхронно
Управление заказами клиентов -> Матчинг: синхронно

Контроль выдачи расходников <- Управление заказами клиентов: асинхронно

Трекер задач <- Управление расчетами с воркерами: синхронно
Трекер задач <- Управление заказами клиентов: асинхронно

Отслеживание заказов <- Управление заказами клиентов: асинхронно

Тотализатор <- Управление заказами клиентов: асинхронно
