vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 1
  }
}

classes: {
  core: {style: {fill: mediumseagreen}}
  supporting: {style: {fill: mediumpurple}}
  generic: {style: {fill: silver}}
}


Найм и матчинг воркеров {
  class: core

  Тестирование и найм
  Матчинг

  Тестирование и найм -> Матчинг
}

Продажа услуг клиентам {
  class: supporting

  Управление заказами клиентов
  Управление расчетами с клиентами

  Управление заказами клиентов -> Управление расчетами с клиентами
  Управление заказами клиентов <- _.Найм и матчинг воркеров.Матчинг
}

УправлениеЗадачами: Управление задачами воркеров {
  class: supporting

  Трекер задач
  Управление расчетами с воркерами

  Трекер задач -> Управление расчетами с воркерами
  Трекер задач <- _.Продажа услуг клиентам.Управление заказами клиентов
}

Сборка расходных материалов {
  class: generic

  Контроль выдачи расходников

  Контроль выдачи расходников <- _.Продажа услуг клиентам.Управление заказами клиентов
}

Контроль качества {
  class: generic

  Отслеживание заказов

  Отслеживание заказов <- _.Продажа услуг клиентам.Управление заказами клиентов
}

Мотивация менеджеров {
  class: supporting

  Тотализатор

  Тотализатор <- _.Продажа услуг клиентам.Управление заказами клиентов
}
